-- Enable useful extensions
create extension if not exists pgcrypto;   -- gen_random_uuid()
create extension if not exists pg_trgm;    -- fast "search text" (ILIKE) via trigram

-- =========
-- Enums
-- =========
do $$ begin
  create type listing_kind as enum ('sale','rent','new_launch','hostel');
exception when duplicate_object then null; end $$;

do $$ begin
  create type listing_status as enum ('draft','published','archived');
exception when duplicate_object then null; end $$;

do $$ begin
  create type currency_code as enum ('MMK','USD','THB');
exception when duplicate_object then null; end $$;

-- =========
-- Reference data
-- =========
create table if not exists regions (
  id          smallint primary key,
  name_mm     text not null,
  name_en     text,
  sort_order  smallint not null default 0
);

create table if not exists townships (
  id          integer generated by default as identity primary key,
  region_id   smallint not null references regions(id) on delete restrict,
  name_mm     text not null,
  name_en     text,
  sort_order  smallint not null default 0,
  unique (region_id, name_mm)
);

create table if not exists property_types (
  id          smallint primary key,
  name_mm     text not null,
  name_en     text,
  sort_order  smallint not null default 0
);

-- =========
-- Agencies / Owners
-- =========
create table if not exists agencies (
  id            uuid primary key default gen_random_uuid(),
  display_name  text not null,
  logo_url      text,
  phone         text,
  email         text,
  created_at    timestamptz not null default now()
);

-- =========
-- Listings
-- =========
create table if not exists listings (
  id                 uuid primary key default gen_random_uuid(),

  -- Public-facing "Ad Number" like S-15385164
  listing_code       text not null unique,

  kind               listing_kind not null,
  status             listing_status not null default 'draft',
  is_featured        boolean not null default false,

  title              text not null,
  description        text,

  region_id          smallint not null references regions(id),
  township_id        integer references townships(id),
  property_type_id   smallint references property_types(id),

  -- Display fields you showed
  floor_label        text,                 -- e.g. '၅ လွှာ'
  bedrooms           smallint,
  bathrooms          smallint,

  -- Dimensions and area
  width_ft           numeric(10,2),
  length_ft          numeric(10,2),
  area_sqft          integer,              -- e.g. 1400
  area_label         text,                 -- optional raw label, e.g. '1400 စတုရန်းပေ'

  -- Pricing (iMyanmarHouse uses "သိန်း (ကျပ်)" frequently)
  currency           currency_code not null default 'MMK',
  price_amount       numeric(14,2),        -- store the number in your chosen unit
  price_unit_label   text,                 -- e.g. 'သိန်း (ကျပ်)' or 'ကျပ်' etc.
  price_per_sqft     numeric(14,4),        -- e.g. 2.7 (သိန်း) per sqft, if applicable

  -- Optional geo
  address_text       text,
  lat                numeric(9,6),
  lng                numeric(9,6),

  -- Ownership
  agency_id          uuid references agencies(id) on delete set null,
  owner_user_id      uuid,                 -- if you later connect to auth.users

  -- Stats (you showed "views: 59")
  views_count        integer not null default 0,

  published_at       timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

-- Keep updated_at fresh
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_listings_updated_at on listings;
create trigger trg_listings_updated_at
before update on listings
for each row execute function set_updated_at();

-- =========
-- Listing Images
-- =========
create table if not exists listing_images (
  id           uuid primary key default gen_random_uuid(),
  listing_id   uuid not null references listings(id) on delete cascade,
  image_url    text not null,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now()
);

create index if not exists idx_listing_images_listing_sort
  on listing_images(listing_id, sort_order);

-- =========
-- Favorites (like your heart button)
-- =========
create table if not exists listing_favorites (
  listing_id   uuid not null references listings(id) on delete cascade,
  user_id      uuid not null,
  created_at   timestamptz not null default now(),
  primary key (listing_id, user_id)
);

-- =========
-- Views (optional, if you want per-view events; you can keep only views_count if you prefer)
-- =========
create table if not exists listing_views (
  id           uuid primary key default gen_random_uuid(),
  listing_id   uuid not null references listings(id) on delete cascade,
  viewer_user_id uuid,
  viewer_ip    inet,
  user_agent   text,
  created_at   timestamptz not null default now()
);

create index if not exists idx_listing_views_listing_created
  on listing_views(listing_id, created_at desc);

-- =========
-- Contact messages (your "message-contact" concept)
-- =========
create table if not exists listing_messages (
  id            uuid primary key default gen_random_uuid(),
  listing_id    uuid not null references listings(id) on delete cascade,
  sender_user_id uuid,
  sender_name   text,
  sender_phone  text,
  sender_email  text,
  message_body  text not null,
  created_at    timestamptz not null default now()
);

create index if not exists idx_listing_messages_listing_created
  on listing_messages(listing_id, created_at desc);

-- =========
-- Reports (your "Report" modal)
-- =========
create table if not exists listing_reports (
  id            uuid primary key default gen_random_uuid(),
  listing_id    uuid not null references listings(id) on delete cascade,
  reporter_user_id uuid,
  reason        text,
  details       text,
  created_at    timestamptz not null default now()
);

create index if not exists idx_listing_reports_listing_created
  on listing_reports(listing_id, created_at desc);

-- =========
-- Search + filter performance
-- =========

-- Filter indexes
create index if not exists idx_listings_kind_status_featured
  on listings(kind, status, is_featured);

create index if not exists idx_listings_region_township_type
  on listings(region_id, township_id, property_type_id);

create index if not exists idx_listings_price
  on listings(currency, price_amount);

create index if not exists idx_listings_bed_bath_area
  on listings(bedrooms, bathrooms, area_sqft);

-- "Text or Ad Number" search:
-- 1) fast exact match for listing_code
create index if not exists idx_listings_listing_code
  on listings(listing_code);

-- 2) trigram for Burmese title/description (better than full-text for Myanmar text in many cases)
create index if not exists idx_listings_title_trgm
  on listings using gin (title gin_trgm_ops);

create index if not exists idx_listings_description_trgm
  on listings using gin (description gin_trgm_ops);

-- =========
-- Triggers / Functions
-- =========

create sequence if not exists listing_code_seq;

create or replace function assign_listing_code()
returns trigger as $$
declare
  n bigint;
  prefix text;
begin
  if new.listing_code is not null and length(new.listing_code) > 0 then
    return new;
  end if;

  n := nextval('listing_code_seq');

  prefix :=
    case new.kind
      when 'sale' then 'S-'
      when 'rent' then 'R-'
      when 'new_launch' then 'N-'
      when 'hostel' then 'H-'
    end;

  -- 8 digits-ish look; adjust padding if you want longer.
  new.listing_code := prefix || lpad(n::text, 8, '0');
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_assign_listing_code on listings;
create trigger trg_assign_listing_code
before insert on listings
for each row execute function assign_listing_code();

-- =========

create or replace function public.search_listings(
  p_q text default null,
  p_kind listing_kind default null,
  p_region_id smallint default null,
  p_township_id integer default null,
  p_property_type_id smallint default null,
  p_min_bed smallint default null,
  p_max_bed smallint default null,
  p_price_from numeric default null,
  p_price_to numeric default null
)
returns table (
  id uuid,
  listing_code text,
  title text,
  region_id smallint,
  township_id integer,
  property_type_id smallint,
  floor_label text,
  area_sqft integer,
  price_amount numeric,
  price_unit_label text,
  is_featured boolean,
  published_at timestamptz,
  views_count integer
)
language sql
stable
as $$
  select
    l.id, l.listing_code, l.title, l.region_id, l.township_id, l.property_type_id,
    l.floor_label, l.area_sqft, l.price_amount, l.price_unit_label,
    l.is_featured, l.published_at, l.views_count
  from listings l
  where l.status = 'published'
    and (p_kind is null or l.kind = p_kind)
    and (p_region_id is null or l.region_id = p_region_id)
    and (p_township_id is null or l.township_id = p_township_id)
    and (p_property_type_id is null or l.property_type_id = p_property_type_id)
    and (p_min_bed is null or coalesce(l.bedrooms,0) >= p_min_bed)
    and (p_max_bed is null or coalesce(l.bedrooms,0) <= p_max_bed)
    and (p_price_from is null or coalesce(l.price_amount,0) >= p_price_from)
    and (p_price_to is null or coalesce(l.price_amount,0) <= p_price_to)
    and (
      p_q is null
      or p_q = ''
      or l.listing_code ilike p_q || '%'
      or l.title ilike '%' || p_q || '%'
      or l.description ilike '%' || p_q || '%'
    )
  order by l.is_featured desc, l.published_at desc nulls last, l.created_at desc;
$$;

---

alter table listings enable row level security;
alter table listing_images enable row level security;
alter table listing_favorites enable row level security;
alter table listing_messages enable row level security;

-- Public read: only published
create policy "public read published listings"
on listings for select
using (status = 'published');

create policy "public read listing images for published listings"
on listing_images for select
using (exists (
  select 1 from listings l
  where l.id = listing_images.listing_id
    and l.status = 'published'
));

-- Owner manage listings (requires auth)
create policy "owner insert listings"
on listings for insert
with check (auth.uid() = owner_user_id);

create policy "owner update own listings"
on listings for update
using (auth.uid() = owner_user_id)
with check (auth.uid() = owner_user_id);

-- Favorites: users manage their own favorites
create policy "user manage own favorites"
on listing_favorites for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Messages: allow authenticated users to create, and only owner can read
create policy "auth users can send message"
on listing_messages for insert
with check (auth.uid() = sender_user_id);

create policy "owner can read messages for own listings"
on listing_messages for select
using (exists (
  select 1 from listings l
  where l.id = listing_messages.listing_id
    and l.owner_user_id = auth.uid()
));
